### ISSUE TITLE
往画板中插入指定素材图片问题

### ISSUE THREAD

**Issue by zftlive** [rhcad/vgandroid#9]
调用 mHelper.insertBitmapFromResource(R.drawable.ic_launcher) 插入指定素材时，四周会自动加上边框，并且出现两条对角线，我跟踪插入代码了发现是JNI实现的，请问该如何去除四周的边框以及对角线
![qq 20150906002912](https://cloud.githubusercontent.com/assets/13717505/9700249/9cb4df88-542e-11e5-9759-355e368b6cec.png)

**Comment by zftlive** [comment]
在调用mHelper.insertBitmapFromResource(R.drawable.ic_launcher) 之后，我自己尝试调用【mHelper.setCommand("select");mHelper.setLineColor(0);】可以去除四周边框以及对角线了。谢谢我自己解决了

**Comment by zengfantian** [comment]
快速点击插入两个元素的时候还是会出现四边框

**Comment by rhcad** [comment]
在 `vgcore/core/src/shape/mgimagesp.cpp` 的 `MgImageShape::_draw` 函数中去掉 `drawBox(gs, ctx)` 就不显示外边框和叉叉了。显示图像失败后才会调用drawBox显示外框和叉叉。

``` cpp
bool MgImageShape::_draw(int, GiGraphics& gs, const GiContext& ctx, int) const
{
    Box2d rect(getRect() * gs.xf().modelToDisplay());
    Vector2d vec((_points[1] - _points[0]) * gs.xf().modelToWorld());
    bool ret = false;

    if (isVisible()) {
        ret = (gs.rawImage(_name, rect.center().x, rect.center().y,
                           rect.width(), rect.height(), vec.angle2())
               || drawBox(gs, ctx));
    }

    return ret;
}
```

**Comment by rhcad** [comment]
显示图像失败后才会调用drawBox显示外框和叉叉。

**Comment by zftlive** [comment]
thanks，已成功去除，重新编译输出so，感谢作者无私的开源奉献

**Comment by rhcad** [comment]
感谢分享经验，希望用好。
